name: 0 - Create Pull Request from dev
on:
  push:
    branches:
      - "dev"

permissions:
  pull-requests: write
  contents: write

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Make changes to pull request
        run: date +%s > report.txt

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.MEUSEGREDO }}
          commit-message: Update report
          committer: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          sign-commits: true
          signoff: false
          branch: ${{ github.ref }}
          base: main
          delete-branch: false
          title: "[Example] Update report"
          body-path: .github/pull_request_template.md
          labels: |
            report
            automated-pr
          assignees: kmaximo
          #reviewers: kmaximo
          milestone: 1
