name: Dev Push CI/CD Pipeline using UV
on:
  push:
    branches:
      - "dev"

jobs:
  dev-test-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      # - name: Install UV package manager
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install uv

      # - name: Install dependencies with UV
      #   run: |
      #     uv pip install -r requirements.txt
      - name: Set environment
        run: |
          echo "ENV=dev" >> $GITHUB_ENV

      # - name: Run pre-deployment checks
      #   run: |
      #     uv pre-deploy

      # - name: Run tests with UV
      #   run: |
      #     uv test --env=$ENV

  createPullRequest:
    needs: [dev-test-and-deploy]
    runs-on: ubuntu-latest
    steps:
      - name: Create Pull Request
        if: success()
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.MEUSEGREDO }}
          commit-message: Update report
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          sign-commits: true
          signoff: false
          branch: ${{ github.ref }}
          base: main
          delete-branch: false
          title: "Auto PR "
          body-path: .github/pull_request_template.md
          labels: |
            automated-pr
          assignees: kmaximo
          #reviewers: kmaximo
          milestone: 1
