name: Main - Build & Deploy
on:
  pull_request:
    types: closed
    branches: main

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: prd
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      # - name: Install UV package manager
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install uv

      # - name: Install dependencies with UV
      #   run: |
      #     uv pip install -r requirements.txt
      - name: Set environment
        run: |
          echo "ENV=prd" >> $GITHUB_ENV

      # - name: Run pre-deployment checks
      #   run: |
      #     uv pre-deploy

      # - name: Run tests with UV
      #   run: |
      #     uv test --env=$ENV
